[project]
name = "false-positives-miner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "dotenv>=0.9.9",
    "pydantic-ai>=2.8.0",
    "python-dotenv>=1.2.2",
    "software-analysis-agent",
    "tree-sitter",
    "tree-sitter-bash>=0.25.1",
    "tree-sitter-java>=0.23.5",
]

[tool.uv.sources]
software-analysis-agent = { git = "https://github.com/islem-esi/software-analysis-agent.git" }
# must use from GitHub, since the latest release does not include a fix for a segfault we run into a lot
tree-sitter = { git = "https://github.com/tree-sitter/py-tree-sitter.git" }
